// <auto-generated />
using System;
using Kolokwium2_Poprawa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium2_Poprawa.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240625142004_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium2_Poprawa.Models.Car_Rentals", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CarID");

                    b.HasIndex("ClientID");

                    b.ToTable("car_rentals");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CarID = 1,
                            ClientID = 1,
                            DateFrom = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            TotalPrice = 480
                        },
                        new
                        {
                            ID = 2,
                            CarID = 1,
                            ClientID = 1,
                            DateFrom = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            TotalPrice = 360
                        },
                        new
                        {
                            ID = 3,
                            CarID = 2,
                            ClientID = 1,
                            DateFrom = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            TotalPrice = 1530
                        },
                        new
                        {
                            ID = 4,
                            CarID = 2,
                            ClientID = 2,
                            DateFrom = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2024, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0,
                            TotalPrice = 340
                        });
                });

            modelBuilder.Entity("Kolokwium2_Poprawa.Models.Cars", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ColorID")
                        .HasColumnType("int");

                    b.Property<int>("ModelID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PricePerDay")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("ID");

                    b.HasIndex("ColorID");

                    b.HasIndex("ModelID");

                    b.ToTable("cars");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ColorID = 1,
                            ModelID = 1,
                            Name = "Camry",
                            PricePerDay = 120,
                            Seats = 4,
                            VIN = "2D4HN11EX9R686008"
                        },
                        new
                        {
                            ID = 2,
                            ColorID = 2,
                            ModelID = 2,
                            Name = "Octavia",
                            PricePerDay = 170,
                            Seats = 4,
                            VIN = "JTDBR32E630013672"
                        });
                });

            modelBuilder.Entity("Kolokwium2_Poprawa.Models.Clients", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("clients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Koszykowa 86",
                            FirstName = "Jan",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Tenkaichi Street",
                            FirstName = "John",
                            LastName = "Yakuza"
                        });
                });

            modelBuilder.Entity("Kolokwium2_Poprawa.Models.Colors", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("colors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "white"
                        },
                        new
                        {
                            ID = 2,
                            Name = "black"
                        });
                });

            modelBuilder.Entity("Kolokwium2_Poprawa.Models.Models", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("models");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Skoda"
                        });
                });

            modelBuilder.Entity("Kolokwium2_Poprawa.Models.Car_Rentals", b =>
                {
                    b.HasOne("Kolokwium2_Poprawa.Models.Cars", "Car")
                        .WithMany()
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2_Poprawa.Models.Clients", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Kolokwium2_Poprawa.Models.Cars", b =>
                {
                    b.HasOne("Kolokwium2_Poprawa.Models.Colors", "Color")
                        .WithMany()
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2_Poprawa.Models.Models", "Model")
                        .WithMany()
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Kolokwium2_Poprawa.Models.Clients", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
